In [5]:
import cv2
img=cv2.imread("w1.jfif")
cv2.imshow("nature", img)
cv2.waitKey(0)
# This is necessary to be required so that the image doesn't close immediately
cv2.destroyAllWindows()#It will run continuously until the key press. 

h, w=img.shape[:2]

print(img.shape)
print(f"height i s{h} and its width is {w}")

cv2.imwrite("nature.png", img)# save image 

(183, 275, 3)
height i s183 and its width is 275


True

In [6]:
px=img[100,100]
print(px)
blue=img[100 , 100 , 0]
print("in bgr blue value is = " ,blue)
green=img[100 , 100 , 1]
print("in bge green value is " , green)
red=img[100 , 100 ,2]
print("in bgr red value is " ,red)
##or like this 
b,g,r=img[100,100]
print(b)
print(g)
print(r)




[194 206 240]
in bgr blue value is =  194
in bge green value is  206
in bgr red value is  240
194
206
240


In [7]:
img.item(10,10,2)
img.item(10,10,1)
img.item(10,10,0)

238

In [8]:
img.dtype
# Splitting and Merging Image Channels
b,g,r=cv2.split(img)
print(b)
print(g)
print(r)




[[238 237 237 ... 209 209 209]
 [238 238 237 ... 209 209 209]
 [238 238 238 ... 210 210 210]
 ...
 [153 139 107 ...  70  69  68]
 [101 107  99 ...  34  34  34]
 [ 93 121 121 ...  65  62  56]]
[[228 227 227 ... 173 173 173]
 [228 228 227 ... 173 173 173]
 [227 227 227 ... 174 174 174]
 ...
 [142 132 100 ...  59  59  57]
 [ 90 100  92 ...  23  23  23]
 [ 82 114 114 ...  53  50  44]]
[[204 203 203 ... 109 109 109]
 [204 204 203 ... 109 109 109]
 [205 205 205 ... 110 110 110]
 ...
 [120 107  73 ...  27  25  25]
 [ 68  75  65 ...   0   0   0]
 [ 60  89  87 ...  25  22  16]]


In [9]:
img[:,:,2]=0  #sets all values in red channel as zero
red=img[:,:,2]
# img[:,:,1]=0 ##set green is set to be zero only blue pic will shown 
print(red)
# img1=cv2.imread("nature.png")


cv2.imshow("red is zero" ,img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Interpolation(optional) – This flag uses following methods:

Interpolation(optional) – This flag uses following methods:
INTER_NEAREST – a nearest-neighbor interpolation
INTER_LINEAR – a bilinear interpolation (used by default) 
INTER_AREA – resampling using pixel area relation. It may be a preferred method for image decimation, as it gives moire’-free results. But when the image is zoomed, it is similar to the INTER_NEAREST method.
INTER_CUBIC – a bicubic interpolation over 4×4 pixel neighborhood 
INTER_LANCZOS4 – a Lanczos interpolation over 8×8 pixel neighborhood

In [10]:
###cv2.resize(s, size,fx,fy,interpolation)
import cv2


img_resize=cv2.resize(img  , (700 ,500) ,interpolation=cv2.INTER_NEAREST)
cv2.imshow("RESIZED IMAGE", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2


# crete method for the resizing the image this work image, video, live vidios
def resize_image(frame , percent=20):
    width=int(frame.shape[1]*percent/100)
    height=int(frame.shape[0]*percent/100)
    dimension=(width , height)
    return cv2.resize(frame,dimension , interpolation= cv.INTER_AREA)


capture=cv2.VideoCapture("cat.mp4") ##if i want to use camera of laptop then instead file name use 0 for laptop camera
while True: ##to read evry fram of the vidio
    
    
    isTrue , frame=capture.read()   ###istrue use for are every frame read coreectly
    cv2.imshow("vidio khan" , frame)
    
    resizeimage=resize_image(frame , 30)
    cv2.imshow("iimage resize" , resizeimage)
    if cv2.waitKey(1)==ord("d"):
        break
capture.release()
cv2.waitKey(0)
cv2.destroyAllWindows()


NameError: name 'cv' is not defined

In [1]:
import cv2 as cv
capt=cv.VideoCapture(0)
while True:
    isTrue , frame=capt.read()
    cv.imshow("camera video", frame)
    if cv.waitKey(1)==ord('d'):
        break
capt.release()
cv.waitKey(0)
cv.destroyAllWindows()
    

In [6]:
capt=cv.VideoCapture(0)
while True:
    isTrue, frame=capt.read()
    cv.imshow("vido is runninng" , frame)
    if cv.waitKey(1)== ord('d'):
        break
capt.release()
cv.waitKey(0)
cv.destroyAllWindows()
    
  

In [ ]:
import cv2 as cv
img=cv.imread("w2.jpg")
cv.imshow("cat" ,img )
# create method for reizeing
def resize_image(frame , percent=20):
    width=int(frame.shape[1]*percent/100)
    height=int(frame.shape[0]*percent/100)
    dimension=(width , height)
    return cv.resize(frame,dimension , interpolation= cv.INTER_NEAREST)

resizeimage=resize_image(img,60)
cv.imshow("iimage resize" , resizeimage)


cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
import numpy as np
blank=np.zeros((300 , 300 , 3) , dtype='uint8')
cv.imshow("bllank" , blank)
blank[:]=0,0,255 ##entire value is this img[:]
cv.imshow("red" , blank)
blank[:]=0,255,0
cv.imshow("green" , blank)
blank[:]=255,0,0
cv.imshow("blue" , blank)

blank[100:200 , 200,300]=0,0,255
cv.imshow("square" , blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
import numpy as np
blank=np.zeros((300 , 300 , 3) , dtype='uint8')
cv.imshow("bllank" , blank)
blank[:]=0,0,255 ##entire value is this img[:]
cv.imshow("red" , blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [5]:
import cv2 as cv
image=cv.imread("w2.jpg")
cv.imshow("image showing" ,image )
grayscale=cv.cvtColor(image, cv.COLOR_BGR2GRAY)
hsvimg=cv.cvtColor(image, cv.COLOR_BGR2HSV)
cmykimg=cv.cvtColor(image, cv.COLOR_BGR2CMYK)



cv.imshow("gray pictur" ,grayscale)
cv.imshow("hsvimage" , hsvimg)
cv.imshow("cmk image" ,cmykimg)


cv.waitKey(0)
cv.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'COLOR_BGR2CMYK'